services:
  patients-db:
    image: postgres:18.1
    container_name: patients-db
    environment:
      - POSTGRES_DB=medilabo_solutions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes: 
      # - postgres_data:/var/lib/postgresql
      # - medilabo_solutions_postgres_data:/var/lib/postgresql # use old volume
      - medilabo_solutions_postgres_data:/var/lib/postgresql

  notes-db:
    image: mongo:8.2.3-noble
    container_name: notes-db
    environment: 
      MONGO_INITDB_DATABASE: medilabo_solutions
    ports: 
      - "27017:27017"
    volumes:
      - medilabo_solutions_mongodb_data:/data/db

  patient-api: 
    image: patient-api:latest 
    container_name: patient-api 
    build:
      context: ./patient-api # folder with patient-api microservice 
      # dockerfile: Dockerfile 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patients-db:5432/medilabo_solutions
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - patients-db    
    restart: on-failure

  notes-api: 
    image: notes-api:latest
    container_name: notes-api
    build:
      context: ./notes-api
    environment:
      # SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/medilabo_solutions
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017/medilabo_solutions
      PATIENT_API_URL: http://host.docker.internal:8080
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - patient-api
      - notes-db
    restart: on-failure

  risk-assessment-api:
    image: risk-assessment-api:latest
    container_name: risk-assessment-api
    build:
      context: ./risk-assessment-api
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017/medilabo_solutions
      PATIENT_API_URL: http://host.docker.internal:8080
      NOTES_API_URL: http://host.docker.internal:8081
      # SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - patient-api
      - notes-api 
    restart: on-failure    

  gateway-api:
    image: gateway-service:latest
    container_name: gateway-service
    build:
      context: ./gateway-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017/medilabo_solutions
      PATIENT_API_URL: http://host.docker.internal:8080
      NOTES_API_URL: http://host.docker.internal:8081
      RISK_ASSESSMENT_API_URL: http://host.docker.internal:8082
      SERVER_PORT: 20000 
    ports:
      - "20000:20000"
    depends_on:
      - patient-api
      - notes-api
      - risk-assessment-api 
    restart: on-failure
    

volumes:
  medilabo_solutions_postgres_data:
  # notes_db_data: 
  medilabo_solutions_mongodb_data: 