# PATIENT_API_URL=http://patient-api:8080
# NOTES_API_URL=http://notes-api:8081
PATIENT_API_URL=http://patient-api:8080
NOTES_API_URL=http://notes-api:8081
server.port=8082

server.error.include-message=always