# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://patients-db:5432/medilabo_solutions
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA and Hibernate settings (optional, common practice)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# server.port=8080
server.address=0.0.0.0
server.port=8080
